language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - composer install

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always
